### ISSUE TITLE
Need to mention what is "secure" with "Secure Endpoint for Metric Registrar"

### ISSUE THREAD

**Issue by AkihiroKitada** [pivotal-cf/docs-pas#170]
According to the release note for "Secure Endpoint for Metric Registrar" feature from TAS 2.12, it's not mentioned on what is "secure" with the new feature.

https://docs.pivotal.io/application-service/2-12/release-notes/runtime-rn.html#secure-metric-registrar
```
TAS for VMs v2.12 allows operators to register a secure endpoint for the Metric Registrar CLI plugin to
ingest app metrics. You can use the cf register-metrics-endpoint command to specify an internal port
in your app when you register the endpoint to the metric registrar.
```

With this new feature, I see that Endpoint Workers scrape metrics by directly accesing to metric endpoints within TAS internal network rather than accesing via LB/Gorouter from internet side of network as previous behavior. This means "secure." In other words, with this new feature, network traffices including metrics data don't go through internet and malicious third party can't inspect those traffices, which means "secure."

Could you add such brife explanation with the release note for the new feature?

**Comment by bobbygeeze** [comment]
@AkihiroKitada I will add the following to the 2.12 release notes: "This new feature makes sure network traffic, including metrics data, does not go through the internet and that malicious third parties cannot inspect the traffic. 

Does that suffice?  Does this information regarding "secure" need to go anywhere else?

**Comment by anita-flegg** [comment]
@bobbygeeze , 2.12 is no longer being updated or published. 
If it important for use, you can add it in 2.13 and just say that it was introduced in 2.12.

**Comment by anita-flegg** [comment]
@AkihiroKitada, if you need this added to the 2.13 release notes, please make a PR and we will merge it. 
I am closing this Issue because no changes are planned for the 2.12 docs.
