### ISSUE TITLE
TAS `3.0.1` released without release notes

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-pas#220]
* https://network.pivotal.io/products/elastic-runtime/#/releases/1201902
* https://docs.pivotal.io/application-service/3-0/release-notes/runtime-rn.html
* https://github.com/pivotal-cf/docs-pas/blob/3.0/runtime-rn.html.md.erb

**Comment by anita-flegg** [comment]
I am seeing the right information at these links. Can we close this PR, or is there more to do?

**Comment by coffee-squirrel** [comment]
This can also be closed-- release notes were eventually added.  Thanks
