### ISSUE TITLE
TAS `2.13.12` and `3.0.2` released without release notes published

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-pas#228]
`2.13.12`:
* https://network.pivotal.io/products/elastic-runtime/#/releases/1214913
* https://docs.pivotal.io/application-service/2-13/release-notes/runtime-rn.html
* https://github.com/pivotal-cf/docs-pas/blob/2.13/runtime-rn.html.md.erb (present but not published)

`3.0.2`:
* https://network.pivotal.io/products/elastic-runtime/#/releases/1214907
* https://docs.pivotal.io/application-service/3-0/release-notes/runtime-rn.html
* https://github.com/pivotal-cf/docs-pas/blob/3.0/runtime-rn.html.md.erb (present but not published)

**Comment by anita-flegg** [comment]
I am seeing release notes at these links. Can this be closed, or is there more to do?

**Comment by coffee-squirrel** [comment]
They've since been added, so this can be closed.  Thank you
