### ISSUE TITLE
Known Issues regarding Metrics Registrar 1.2.1 

### ISSUE THREAD

**Issue by louis-brann** [pivotal-cf/docs-pas#33]
Hi there,

We incorporated version 1.2.1 of Metrics Registrar into TAS 2.7-2.10, which introduced a couple of features and a couple of upgrade-blocking bugs. We reverted it in the subsequent patch release on each affected minor version of TAS, but we want to document the known issues. Making one issue to track all of the associated PRs here.

There are 3 issues to note, and of the three, two are definitely resolved by the revert. It is not entirely clear whether the revert of the metric-registrar bump will fully solve the third, so we left out the "resolved in v2.10.5 and later" message for that one.

Affected Versions:
- TAS 2.7.24: https://github.com/pivotal-cf/docs-pas/pull/34
- TAS 2.8.18: https://github.com/pivotal-cf/docs-pas/pull/35
- TAS 2.9.12: https://github.com/pivotal-cf/docs-pas/pull/36
- TAS 2.10.4: https://github.com/pivotal-cf/docs-pas/pull/37

**Comment by mlimonczenko** [comment]
Hello @louis-brann,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
