### ISSUE TITLE
Typo in 6.0 release notes

### ISSUE THREAD

**Issue by Gerg** [pivotal-cf/docs-pas#358]
### Describe the bug

Regarding https://github.com/pivotal-cf/docs-pas/blob/8b15d4786a851ee7c63b176ce9938ed477dad626/runtime-rn.html.md.erb#L1824C1-L1824C45:

> Operators can continue to [Cloud Controller](https://docs.vmware.com/en/VMware-Tanzu-Application-Service/6.0/tas-for-vms/config-cloud-controller.html) to install cflinuxfs3, if desired.

This sentence doesn't make sense as written. I propose:

> Operators can continue to *configure* [Cloud Controller](https://docs.vmware.com/en/VMware-Tanzu-Application-Service/6.0/tas-for-vms/config-cloud-controller.html) to install cflinuxfs3, if desired.

### Reproduction steps

Read TAS 6.0 breaking changes.

### Expected behavior

Grammar occurs.

**Comment by anita-flegg** [comment]
Fixed
